// yeet2waifu © 2026 Haru (@haru717171x). All rights reserved. Free to play on stream; see LICENSE.
// The waifus that ship with the game: ORIGINAL characters built on familiar archetypes (the streamer picks
// one with ?waifu=<id> or !y2w waifu <id>, or pastes a waifu code made in the editor; see waifucode.js).
// Recognizable parodies are NOT here on purpose: they travel as codes, outside the repo.
// 32×32, same ENDESGA 32 palette as everything else.
import { sprite } from './raster.js';
import { decodeWaifu } from '../waifucode.js';

const KEY = {
  d: 'bark', H: 'amber', h: 'orange', y: 'yellow', F: 'peach', f: 'skin', E: 'ink', e: 'blue', n: 'navy',
  c: 'cyan', W: 'white', M: 'crimson', B: 'rose', R: 'hot', r: 'crimson', D: 'white', s: 'silver', p: 'rose',
  K: 'bark', L: 'slate',
};

export const WAIFUS = {
  hana: {
    name: 'Hana',
    blurb: 'the sweetheart with the big red bow',
    img: sprite(KEY, `
....................dd...dd.....
............ddddddddRRd.dRRd....
...........dHHHHHHdRRRRdRRRRd...
.........dHyyHHHHHdRrRRrRRrRd...
........dHyyHyHHHHHdrrdRdrrd....
.......dHyyHHHHHHHHHddHdddd.....
.......dHHHHHHHHHHHHHHHHd.......
.......dHHHHHHHHHHHHHHHHd.......
......ddHHhHhHHhHhHHhHHHdd......
......dHHHHHFHHHFHHHFHHHHd......
......dHHHHFFFHFFFHFFFHHHd......
......dHHHEFFFFFFFFFFEHHHd......
.....dHhHFEEEEFFFFEEEEFHhHd.....
.....dHhHFFWenFFFFWenFFHhHd.....
.....dHhHFFeneFFFFeneFFHhHd.....
.....dHhHHFeceFFFFeceFHHhHd.....
.....dHhHHBBFFFMMFFFBBHHhHd.....
.....dHhHH..fFFFFFFf..HHhHd.....
.....dHhHH.....ff.....HHhHd.....
.....dHhHH.LppppppppL.HHhHd.....
.....dHhHLFLDDrRRrDsLFLHhHd.....
.....dHhHLFLDDDrrDDsLFLHhHd.....
.....dHhHLFDDDDDDDDDsFLHhHd.....
.....dHhHLFDDDDDDDDDsFLHhHd.....
.....dHhHLFDDDDDDDDDsFLHhHd.....
......dHhLfDDDDDDDDDDfLhHd......
......dHhLDDDDDDDDDDDsLhHd......
......dddLDDDDDDDDDDDsLddd......
.......LppppppppppppppppL.......
........LLLLLLLLLLLLLLLL........
.............FF..FF.............
............KKK..KKK............
`),
  },
  rosa: {
    name: 'Rosa',
    blurb: 'the princess in pink, waiting in her tower',
    img: sprite({ A: 'amber', B: 'rose', E: 'ink', F: 'peach', G: 'cyan', H: 'rose', K: 'bark', L: 'plum', M: 'crimson', O: 'hot', W: 'white', a: 'yellow', c: 'cyan', d: 'grape', e: 'blue', f: 'skin', h: 'magenta', n: 'navy', o: 'crimson', p: 'white', y: 'white' }, `
...............AA...............
............dAAGGAAd............
...........daAAAAAAad...........
.........dHyyHHHHHHHHHd.........
........dHyyHyHHHHHHHHHd........
.......dHyyHHHHHHHHHHHHHd.......
.......dHHHHHHHHHHHHHHHHd.......
.......dHHHHHHHHHHHHHHHHd.......
......ddHHhHhHHhHhHHhHHHdd......
......dHHHHHFHHHFHHHFHHHHd......
......dHHHHFFFHFFFHFFFHHHd......
......dHHHEFFFFFFFFFFEHHHd......
.....dHhHFEEEEFFFFEEEEFHhHd.....
.....dHhHFFWenFFFFWenFFHhHd.....
.....dHhHFFeneFFFFeneFFHhHd.....
.....dHhHHFeceFFFFeceFHHhHd.....
.....dHhHHBBFFFMMFFFBBHHhHd.....
.....dHhHH..fFFFFFFf..HHhHd.....
.....dHhHH.....ff.....HHhHd.....
.....dHhHH.LppppppppL.HHhHd.....
....HHHhHLFLOOOGGOOoLFLHhHHH....
....dhHhHLFLOOOGGOOoLFLHhHhd....
.....HHhHLFOOOGppGOOoFLHhHH.....
....hHHhHLFOOOOppOOOoFLHhHHh....
....dHHhHLFOOOOppOOOOFLHhHHd....
.....hHHLLfOOOOppOOOOfLLHHh.....
....HHdHLOOOOOOppOOOOOoLHdHH....
....dhHdLOOOOOOppOOOOOoLdHhd....
....ddLppppppppppppppppppLdd....
.......LLLLLLLLLLLLLLLLLL.......
.............FF..FF.............
............KKK..KKK............
`),
  },
  momo: {
    name: 'Momo',
    blurb: 'cat hoodie, toy hammer, zero patience',
    img: sprite({ A: 'red', B: 'rose', E: 'ink', F: 'peach', G: 'white', H: 'orange', K: 'bark', L: 'forest', M: 'crimson', O: 'lime', W: 'white', a: 'brown', c: 'cyan', d: 'bark', e: 'green', f: 'skin', h: 'clay', n: 'forest', o: 'green', p: 'white' }, `
.........L............L.........
.........LO.LLLLLLLL.OL.........
.........LBOOOOOOOOOOBL.........
.........OBOOOOOOOOOOBO.........
........LOOOOOOOOOOOOOOL........
.......LOOOOOOOOOOOOOOOOL.......
.......LOOOOOOOOOOOOOOOOL.......
.......LOOOOOOOOOOOOOOOOL.......
......dLOHhHhHHhHhHHhHHOLd......
......LOHHHHhHHHhHHFFFHHOL......
......LOHHHhHhFFFFFFFFH.LLLLLL..
......LOHHEFFFFFFFFFFELKGGGGGGKL
......LOOFEEEEFFFFEEEELKAAAAAAKL
......LOOFFWenFFFFWenFLKAAAAAAKL
......LOOFFeneFFFFeneFLKAAAAAAKL
......LOOHFeceFFFFeceFLKAAAAAAKL
......LOOHBBFFfMMWFFBBHOLLLLLL..
......LOOH..fFFFFFFf..HOOLaK....
......LOOH.....ff.....HOOLaK....
.......ddd.LppppppppL.ddd.aK....
.........LFLOOWOOWOoLFL...aK....
.........LFLOOWOOWOoLFFFFFaK....
.........LFOOOOOOOOOoFL...aK....
.........LFOOOOOOOOOoFL...aK....
.........LFOOooooooOoFL...aK....
.........LfOOOOOOOOOOfL...aK....
.........LOOOOOOOOOOOoL...aK....
.........LOOOOOOOOOOOoL...aK....
.......LppppppppppppppppL.aK....
........LLLLLLLLLLLLLLLL........
.............FF..FF.............
............KKK..KKK............
`),
  },
  aoi: {
    name: 'Aoi',
    blurb: 'blue knight with a tiara and a sword',
    img: sprite({ A: 'amber', B: 'rose', E: 'ink', F: 'peach', G: 'silver', H: 'blue', K: 'bark', L: 'night', M: 'crimson', O: 'navy', W: 'white', a: 'crimson', c: 'cyan', d: 'night', e: 'cyan', f: 'skin', h: 'navy', n: 'blue', o: 'steel', p: 'silver', y: 'cyan' }, `
...............AA...............
.....G......dAAGGAAd............
.....W.....daAAAAAAad...........
....LGG..dHyyHHHHHHHHHdHhHd.....
....LGW.dHyyHyHHHHHHHHHdHHd.....
....LGGdHyyHHHHHHHHHHHHHdHd.....
....LGGdHHHHHHHHHHHHHHHHdHHd....
....LGGdHHHHHHHHHHHHHHHHdhHd....
....LGWdHHhHhHHhHhHHhHHHdHHd....
....LGGHHHHHFHHHFHHHFHHHHHHHd...
....LGGHHHHFFFHFFFHFFFHHHHHHd...
....LGGHHHEFFFFFFFFFFEHHHHhHd...
....LGWHHFEEEEFFFFEEEEFHHdHHHd..
....LGGHHFFWenFFFFWenFFHHdHHHd..
....LGGHHFFeneFFFFeneFFHHdHHHd..
....LGGHHHFeceFFFFeceFHHHdHhHd..
....LGWHHHBBFFFMMFFFBBHHHdHHHd..
....LGGddd..fFFFFFFf..ddd.HHHd..
....LGGLaaaaaaaffaaaaaaaL.HHHd..
....LGGLaaaLppppppppLaaaL.HhHd..
...AAAAAALFLOOOOOOOoLFLaL.HHHd..
.....aaFFFFLOOOOOOOoLFLaL.HHHd..
.....aaLaLFOOOOOOOOOoFLaL.HHHd..
.....AALaLFOAAAGGAAAoFLaL.HhHd..
.......LaLFOOOOOOOOOoFLaL.ddd...
.......LaLfOOOOOOOOOOfLaL.......
.......LaLOOOOOOOOOOOoLaL.......
.......LaLOOOOOOOOOOOoLaL.......
.......LppppppppppppppppL.......
.......LLLLLLLLLLLLLLLLLL.......
........LLLLLFFLLFFLLLLL........
............KKK..KKK............
`),
  },
  kuro: {
    name: 'Kuro',
    blurb: 'a bratty little demon who thinks you will never reach her',
    img: sprite({ A: 'crimson', E: 'ink', F: 'peach', G: 'grape', H: 'white', K: 'bark', L: 'steel', M: 'crimson', O: 'ink', W: 'white', a: 'bark', c: 'white', d: 'slate', e: 'red', f: 'skin', h: 'silver', n: 'crimson', o: 'night', p: 'red', y: 'white' }, `
...........A........A...........
..........A.dddddddd.A..........
..........AdHHHHHHHHdA..........
.........dayyHHHHHHHHad.........
........dHyyHyHHHHHHHHHd........
.......dHyyHHHHHHHHHHHHHd.......
.......dHHHHHHHHHHHHHHHHd.......
.......dHHHHHHHHHHHHHHHHd.......
......ddHHhHhHHhHhHHhHHHdd......
......dHHHHHhHHHhHHHhHHHHd......
......dHHHHhHhHhHhHhHhHHHd......
......dHHHEFFFFFFFFFFEHHHd......
.....dHhHFEEEEFFFFEEEEFHhHd.....
.....dHhHFFEEEFFFFEEEFFHhHd.....
.....dHhHFFWenFFFFWenFFHhHd.....
.....dHhHHFeceFFFMeceFHHhHd.....
.....dHhHHFfFFfMMFFFfFHHhHd.....
...GLdHhHH..fFFFWFFf..HHhHdGL...
...LGdHhHH.....ff.....HHhHdLG...
...GGdHhHH.LppppppppL.HHhHdGG...
...GLdHhHLFLOOAAAAOoLFLHhHdGL...
...LGdHhHLFLOOOAAOOoLFLHhHdLG...
...GGdHhHLFOOOOOOOOOoFLHhHdGG...
...GLdHhHLFOOOOOOOOOoFLHhHdGL...
...LGdHhHLFOOOOOOOOOoFLHhHdLG...
......dHhLfOOOOOOOOOOfLhHd......
......dHhLOOOOOOOOOOOoLhHd......
......ddpLpOpOpOpOpOpopddd......
.......LppppppppppppppppL.......
........LLLLLLLLLLLLLLLL........
.............FF..FF.............
............KKK..KKK............
`),
  },
};

export const DEFAULT_WAIFU = 'hana';

// An id from WAIFUS, or a waifu code; anything unreadable falls back to the default.
export function resolveWaifu(idOrCode) {
  if (idOrCode && WAIFUS[idOrCode]) return { id: idOrCode, ...WAIFUS[idOrCode] };
  if (idOrCode) {
    const w = decodeWaifu(idOrCode);
    if (w) return { id: 'custom', name: w.name, img: w.img };
  }
  return { id: DEFAULT_WAIFU, ...WAIFUS[DEFAULT_WAIFU] };
}

export const waifuSprite = (idOrCode) => resolveWaifu(idOrCode).img;
export const waifuName = (idOrCode) => resolveWaifu(idOrCode).name;
